spring:
  application:
    name: mail-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: tongsure45@gmail.com
    password: wdznjmquhoegglsn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

server:
  port: 8090
  servlet:
    context-path: /mailservice

